import type { Metadata } from 'next'
import Provider from '@/provider/provider'
import './globals.css'

export const metadata: Metadata = {
  title: 'Next-board',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Provider>
      <body>{children}</body>
      </Provider>
    </html>
  )
}
